#!/bin/bash

#PBS -l nodes=1:ppn=28,walltime=08:00:00
#PBS -N map
#PBS -q long 

sed -i "/$POP.*$/ s/$/ running.../" "/$batchloc/status.txt"

cd "$fastqloc/Sample_"$POP"/fastq"
mkdir map

module load shared
module load torque
module load anaconda/2
module load gnu-parallel

parallel bwa bwasw -t 3 "$fastqloc/consensus.te.fasta" {1} ">" map/{.}.sam ::: *R$I*


wait

sed -i "/$POP.*$/ s/ running.../ merged/" "/$batchloc/status.txt"