#!/bin/bash 

#PBS -l nodes=1:ppn=28,walltime=03:00:00
#PBS -N merge
#PBS -q short 

sed -i "/$POP.*$/ s/$/ running.../" "/$batchloc/status.txt"

mkdir $fastloc/bams/Sample_"${POP::-5}"_bams/
cd "$fastqloc/Sample_"$POP"/fastq/map/merged"

module load shared
module load torque
module load anaconda/2

samtools merge $POP"_te.merged.bam" * > mkdir $fastloc/bams/Sample_"${POP::-5}"_bams/

wait

sed -i "/$POP.*$/ s/ running.../ merged/" "/$batchloc/status.txt"
