#!/bin/bash 

#PBS -l nodes=1:ppn=28,walltime=08:00:00
#PBS -N pileup
#PBS -q long 


cd $fastqloc"/Sample_"$POP"/fastq/map/te"

java -jar popte2.jar ppileup --bam $POP"_te.merged.bam" --map-qual 15 --hier $fastqloc"/tehier.txt" --output $POP.ppileup
